views.view.activity_stream_notifications:
  expected_config: {  }
  update_actions:
    add:
      default:
        display_options:
          filters:
            activity_aggregate_gc:
              admin_label: ''
              entity_type: activity
              expose:
                description: ''
                identifier: ''
                label: ''
                multiple: false
                operator: ''
                operator_id: ''
                operator_limit_selection: false
                operator_list: {  }
                remember: false
                remember_roles:
                  authenticated: authenticated
                required: false
                use_operator: false
              exposed: false
              field: activity_aggregate_gc
              group: 1
              group_info:
                default_group: All
                default_group_multiple: {  }
                description: ''
                group_items: {  }
                identifier: ''
                label: ''
                multiple: false
                optional: true
                remember: false
                widget: select
              group_type: group
              id: activity_aggregate_gc
              is_grouped: false
              operator: '='
              plugin_id: activity_aggregate_gc
              relationship: none
              table: activity
              value: ''
message.template.create_content_in_joined_group:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_entity_condition: group_content_node_single_group
