name: Drupal coding standards

on: [pull_request]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          installed_paths: '${{ github.workspace }}/.composer/vendor/drupal/coder/coder_sniffer'
