name: PHP Stan
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          CHECK_PLATFORM_REQUIREMENTS: false
          REQUIRE_DEV: true
        with:
          args: analyse .
